### ISSUE TITLE
Channel only contains OSX builds

### ISSUE THREAD

**Issue by Yurlungur** [moble/conda-lal#1]
I notice your channel on anaconda cloud only contains OSX builds. Would you be willing to submit these builds to [Conda-Forge](https://conda-forge.github.io/)? Then they'll be in a centralized place and automatically cross-compiled. I would be willing to help set that up if you're interested.

**Comment by moble** [comment]
See my comments on [the other issue](https://github.com/moble/conda-lal/issues/2#issuecomment-310470664).
