### ISSUE TITLE
Version control targets only valid for members of LSC

### ISSUE THREAD

**Issue by Yurlungur** [moble/conda-lal#2]
If possible, it would be nice if the version control targets worked for non-members of the LSC.

**Comment by moble** [comment]
Actually, I never got this entirely working myself, and just gave up after a while.  There were too many contradictions in the public build instructions, secret-sauce tricks that weren't included in the instructions, etc.  I'm barely an LSC member now, and this was from before I was any kind of member, so presumably I had the same problems as you're running into.

Also, I recently saw somebody mention a public docker image for pycbc.  (Maybe [this](https://ligo-cbc.github.io/pycbc/latest/html/docker.html)?)  So next time I want to use any of these things, I'll probably try that first.

Given those points, I consider this repo dead.  Feel free to fork it and continue development if you see a need for it.  But I'm just going to add a disclaimer to the README, and call it closed.
